### ISSUE TITLE
可能是Swagger转Word更好的方式

### ISSUE THREAD

**Issue by Sayi** [JMCuixy/swagger2word#36]
Hi，@JMCuixy

我这里有个swagger word单元测试的小demo，不妨看看能不能获得促进这个项目往前进一步的灵感。

[poi-tl的Swagger Word文档示例](http://deepoove.com/poi-tl/#example-swagger)

**Comment by tangkaichuan** [comment]
感谢，借用您的 example 做了一个粗略的独立项目。
https://github.com/ClearStudio/swagx

**Comment by Sayi** [comment]
@tangkaichuan Good Job!
