### ISSUE TITLE
提示如下。。不晓得是什么问题

### ISSUE THREAD

**Issue by rabbitFS** [JMCuixy/swagger2word#37]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jul 15 09:41:09 CST 2020
There was an unexpected error (type=Internal Server Error, status=500).
An error happened during template parsing (template: "class path resource [templates/word.html]")

**Comment by rabbitFS** [comment]
调整路径之后提示如下内容
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jul 15 09:50:01 CST 2020
There was an unexpected error (type=Internal Server Error, status=500).
Error resolving template "word", template might not exist or might not be accessible by any of the configured Template Resolvers

**Comment by ruandao** [comment]
我也碰到这个问题，估计是swagger 文档不规范导致的
